# Name of the workflow (shown in GitHub Actions UI)
name: CI-CD Pipeline

# --------------------------------------------------
# EVENTS
# --------------------------------------------------
# This workflow will run when:
# 1. Code is pushed to the repository
# 2. A pull request is created or updated
on:
  push:
  pull_request:

# --------------------------------------------------
# JOBS
# --------------------------------------------------
jobs:

  # ==============================
  # CI JOB (Build, Test, Validate)
  # ==============================
  ci:
    # The OS on which the job will run
    runs-on: ubuntu-latest

    # Strategy allows running the same job multiple times
    # Here we are testing across multiple Python versions
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    # Steps are executed sequentially
    steps:

      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python based on matrix version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # This dynamically picks Python version from matrix
          python-version: ${{ matrix.python-version }}

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          # Upgrade pip to latest version
          python -m pip install --upgrade pip
          # Install dependencies listed in requirements.txt
          pip install -r requirements.txt

      # Step 4: Run linting using flake8
      - name: Run linting (flake8)
        # flake8 checks for syntax errors and style issues
        run: flake8 .

      # Step 5: Check code formatting using black
      - name: Check formatting (black)
        # --check ensures black only validates formatting
        run: black --check .

      # Step 6: Run security scan using bandit
      - name: Security scan (bandit)
        # -r app means recursively scan the app directory
        run: bandit -r app

      # Step 7: Run unit tests using pytest
      - name: Run tests (pytest)
        # pytest runs all test files (test_*.py or *_test.py)
        run: pytest

  # ==============================
  # CD JOB (Deploy)
  # ==============================
  cd:
    # This job will only run AFTER ci job succeeds
    needs: ci

    # Deploy only when code is pushed to main branch
    if: github.ref == 'refs/heads/main'

    # OS for deployment
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the code again (each job is isolated)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (single version is enough for deployment)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy application
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Example deployment commands:
          # docker build -t myapp .
          # docker push myapp
          # ssh user@server "docker pull myapp && docker run ..."
